//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineNET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineNET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP アドレスを BAN 一覧に追加します。.
        /// </summary>
        internal static string commands_ban_description {
            get {
                return ResourceManager.GetString("commands_ban_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレイヤー {0} をアクセス禁止にしました.
        /// </summary>
        internal static string commands_ban_success {
            get {
                return ResourceManager.GetString("commands_ban_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP アドレスを BAN 一覧に追加します。.
        /// </summary>
        internal static string commands_banip_description {
            get {
                return ResourceManager.GetString("commands_banip_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無効な IP アドレスが入力されたか、プレイヤーがオンラインになっていません.
        /// </summary>
        internal static string commands_banip_invalid {
            get {
                return ResourceManager.GetString("commands_banip_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP アドレス {0} をアクセス禁止にしました.
        /// </summary>
        internal static string commands_banip_success {
            get {
                return ResourceManager.GetString("commands_banip_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} に属する IP アドレス {0} をアクセス禁止にしました.
        /// </summary>
        internal static string commands_banip_success_players {
            get {
                return ResourceManager.GetString("commands_banip_success_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレイヤーからオペレーターのステータスを取り消す。.
        /// </summary>
        internal static string commands_deop_description {
            get {
                return ResourceManager.GetString("commands_deop_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} からオペレーター権限を剥奪しました.
        /// </summary>
        internal static string commands_deop_success {
            get {
                return ResourceManager.GetString("commands_deop_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステータス効果を追加/除去します。.
        /// </summary>
        internal static string commands_effect_description {
            get {
                return ResourceManager.GetString("commands_effect_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} は効果を受けていないので、除去できませんでした.
        /// </summary>
        internal static string commands_effect_failure_notActive_all {
            get {
                return ResourceManager.GetString("commands_effect_failure_notActive_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} に効果を付与することはできません.
        /// </summary>
        internal static string commands_effect_failure_notAMob {
            get {
                return ResourceManager.GetString("commands_effect_failure_notAMob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} に {0} * {1} を {3} 秒間与えました.
        /// </summary>
        internal static string commands_effect_success {
            get {
                return ResourceManager.GetString("commands_effect_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} からすべての効果を除去しました.
        /// </summary>
        internal static string commands_effect_success_removed_all {
            get {
                return ResourceManager.GetString("commands_effect_success_removed_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択中のエンチャントは対象のアイテムに付加できません: {0}.
        /// </summary>
        internal static string commands_enchant_cantEnchant {
            get {
                return ResourceManager.GetString("commands_enchant_cantEnchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択中のプレイヤーのアイテムにエンチャントを付与する。.
        /// </summary>
        internal static string commands_enchant_description {
            get {
                return ResourceManager.GetString("commands_enchant_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} はレベル {1} に対応していません.
        /// </summary>
        internal static string commands_enchant_invalidLevel {
            get {
                return ResourceManager.GetString("commands_enchant_invalidLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} のエンチャントに成功しました.
        /// </summary>
        internal static string commands_enchant_success {
            get {
                return ResourceManager.GetString("commands_enchant_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレイヤーのゲーム モードを設定する。.
        /// </summary>
        internal static string commands_gamemode_description {
            get {
                return ResourceManager.GetString("commands_gamemode_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to §cゲーム モード &apos;{0}&apos; は無効です.
        /// </summary>
        internal static string commands_gamemode_fail_invalid {
            get {
                return ResourceManager.GetString("commands_gamemode_fail_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} のゲームモードを {0} に設定しました.
        /// </summary>
        internal static string commands_gamemode_success_other {
            get {
                return ResourceManager.GetString("commands_gamemode_success_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたのゲームモードを {0} に設定しました.
        /// </summary>
        internal static string commands_gamemode_success_self {
            get {
                return ResourceManager.GetString("commands_gamemode_success_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to §cセレクターに合う対象がありません .
        /// </summary>
        internal static string commands_generic_noTargetMatch {
            get {
                return ResourceManager.GetString("commands_generic_noTargetMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実装されていません.
        /// </summary>
        internal static string commands_generic_notimplemented {
            get {
                return ResourceManager.GetString("commands_generic_notimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to §c指定されたプレイヤーが見つかりません.
        /// </summary>
        internal static string commands_generic_player_notFound {
            get {
                return ResourceManager.GetString("commands_generic_player_notFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to §cセレクターはプレイヤーの型にする必要があります .
        /// </summary>
        internal static string commands_generic_targetNotPlayer {
            get {
                return ResourceManager.GetString("commands_generic_targetNotPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to §c不明なコマンド: {0}。このコマンドが存在し、これを使用する権限があることを確認してください.
        /// </summary>
        internal static string commands_generic_unknown {
            get {
                return ResourceManager.GetString("commands_generic_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレイヤーにアイテムを与える。.
        /// </summary>
        internal static string commands_give_description {
            get {
                return ResourceManager.GetString("commands_give_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} に {0} を {1} 個与えました .
        /// </summary>
        internal static string commands_give_success {
            get {
                return ResourceManager.GetString("commands_give_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} を {1}個受け取りました .
        /// </summary>
        internal static string commands_give_successRecipient {
            get {
                return ResourceManager.GetString("commands_give_successRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドのヘルプ/一覧を呼び出す。.
        /// </summary>
        internal static string commands_help_description {
            get {
                return ResourceManager.GetString("commands_help_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- ヘルプ ページの {0} ／ {1} ページを表示 (/help &lt;ページ番号&gt;) ---.
        /// </summary>
        internal static string commands_help_header {
            get {
                return ResourceManager.GetString("commands_help_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバー上のプレイヤーの一覧を表示する。.
        /// </summary>
        internal static string commands_list_description {
            get {
                return ResourceManager.GetString("commands_list_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたに関するメッセージを表示します。.
        /// </summary>
        internal static string commands_me_description {
            get {
                return ResourceManager.GetString("commands_me_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレイヤーにオペレーターのステータスを与える。.
        /// </summary>
        internal static string commands_op_description {
            get {
                return ResourceManager.GetString("commands_op_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} にオペレーター権限を付与しました.
        /// </summary>
        internal static string commands_op_success {
            get {
                return ResourceManager.GetString("commands_op_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チャットで他のプレイヤーにメッセージを送信する_.
        /// </summary>
        internal static string commands_say_description {
            get {
                return ResourceManager.GetString("commands_say_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーを停止する。.
        /// </summary>
        internal static string commands_stop_description {
            get {
                return ResourceManager.GetString("commands_stop_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 人または複数のプレイヤーにプライベート メッセージを送信する。.
        /// </summary>
        internal static string commands_tell_description {
            get {
                return ResourceManager.GetString("commands_tell_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレイヤー {0} のアクセス禁止を解除できませんでした.
        /// </summary>
        internal static string commands_unban_failed {
            get {
                return ResourceManager.GetString("commands_unban_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレイヤー {0} のアクセス禁止を解除しました.
        /// </summary>
        internal static string commands_unban_success {
            get {
                return ResourceManager.GetString("commands_unban_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPアドレスが無効です.
        /// </summary>
        internal static string commands_unbanip_invalid {
            get {
                return ResourceManager.GetString("commands_unbanip_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP アドレス {0} のアクセス禁止を解除しました.
        /// </summary>
        internal static string commands_unbanip_success {
            get {
                return ResourceManager.GetString("commands_unbanip_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} をホワイトリストに追加しました.
        /// </summary>
        internal static string commands_whitelist_add_success {
            get {
                return ResourceManager.GetString("commands_whitelist_add_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーのホワイトリストを管理する。.
        /// </summary>
        internal static string commands_whitelist_description {
            get {
                return ResourceManager.GetString("commands_whitelist_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホワイトリストを無効にしました.
        /// </summary>
        internal static string commands_whitelist_disabled {
            get {
                return ResourceManager.GetString("commands_whitelist_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホワイトリストを有効にしました.
        /// </summary>
        internal static string commands_whitelist_enabled {
            get {
                return ResourceManager.GetString("commands_whitelist_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホワイトリストには {0} 人 (サーバー全体では {1} 人) のプレイヤーがいます:.
        /// </summary>
        internal static string commands_whitelist_list {
            get {
                return ResourceManager.GetString("commands_whitelist_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} をホワイトリストから削除しました.
        /// </summary>
        internal static string commands_whitelist_remove_success {
            get {
                return ResourceManager.GetString("commands_whitelist_remove_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレイヤーの経験値を増加/減少させます.
        /// </summary>
        internal static string commands_xp_description {
            get {
                return ResourceManager.GetString("commands_xp_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレイヤーに負の経験値を与えることはできません.
        /// </summary>
        internal static string commands_xp_failure_widthdrawXp {
            get {
                return ResourceManager.GetString("commands_xp_failure_widthdrawXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} に経験値 {0} を与えまし.
        /// </summary>
        internal static string commands_xp_success {
            get {
                return ResourceManager.GetString("commands_xp_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} に {0} レベルを付与しました.
        /// </summary>
        internal static string commands_xp_success_levels {
            get {
                return ResourceManager.GetString("commands_xp_success_levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} から {0} レベルを剥奪しました.
        /// </summary>
        internal static string commands_xp_success_negative_levels {
            get {
                return ResourceManager.GetString("commands_xp_success_negative_levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吸収.
        /// </summary>
        internal static string effect_absorption {
            get {
                return ResourceManager.GetString("effect_absorption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目つぶし.
        /// </summary>
        internal static string effect_blindness {
            get {
                return ResourceManager.GetString("effect_blindness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 毒.
        /// </summary>
        internal static string effect_fatal_poison {
            get {
                return ResourceManager.GetString("effect_fatal_poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 耐火.
        /// </summary>
        internal static string effect_fire_resistance {
            get {
                return ResourceManager.GetString("effect_fire_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勤勉.
        /// </summary>
        internal static string effect_haste {
            get {
                return ResourceManager.GetString("effect_haste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPブースト.
        /// </summary>
        internal static string effect_health_boost {
            get {
                return ResourceManager.GetString("effect_health_boost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空腹.
        /// </summary>
        internal static string effect_hunger {
            get {
                return ResourceManager.GetString("effect_hunger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダメージ.
        /// </summary>
        internal static string effect_instant_damage {
            get {
                return ResourceManager.GetString("effect_instant_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回復.
        /// </summary>
        internal static string effect_instant_health {
            get {
                return ResourceManager.GetString("effect_instant_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可視.
        /// </summary>
        internal static string effect_invisibility {
            get {
                return ResourceManager.GetString("effect_invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳躍.
        /// </summary>
        internal static string effect_jump_boost {
            get {
                return ResourceManager.GetString("effect_jump_boost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮遊.
        /// </summary>
        internal static string effect_levitation {
            get {
                return ResourceManager.GetString("effect_levitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 疲労.
        /// </summary>
        internal static string effect_mining_fatigue {
            get {
                return ResourceManager.GetString("effect_mining_fatigue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目まい.
        /// </summary>
        internal static string effect_nausea {
            get {
                return ResourceManager.GetString("effect_nausea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗視.
        /// </summary>
        internal static string effect_night_vision {
            get {
                return ResourceManager.GetString("effect_night_vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 毒.
        /// </summary>
        internal static string effect_poison {
            get {
                return ResourceManager.GetString("effect_poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再生.
        /// </summary>
        internal static string effect_regeneration {
            get {
                return ResourceManager.GetString("effect_regeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 耐性.
        /// </summary>
        internal static string effect_resistance {
            get {
                return ResourceManager.GetString("effect_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 飽和.
        /// </summary>
        internal static string effect_saturation {
            get {
                return ResourceManager.GetString("effect_saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鈍化.
        /// </summary>
        internal static string effect_slowness {
            get {
                return ResourceManager.GetString("effect_slowness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スピード.
        /// </summary>
        internal static string effect_speed {
            get {
                return ResourceManager.GetString("effect_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 力.
        /// </summary>
        internal static string effect_strength {
            get {
                return ResourceManager.GetString("effect_strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水中呼吸.
        /// </summary>
        internal static string effect_water_breathing {
            get {
                return ResourceManager.GetString("effect_water_breathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弱体化.
        /// </summary>
        internal static string effect_weakness {
            get {
                return ResourceManager.GetString("effect_weakness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィザー.
        /// </summary>
        internal static string effect_wither {
            get {
                return ResourceManager.GetString("effect_wither", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水中作業.
        /// </summary>
        internal static string enchantment_aqua_affinity {
            get {
                return ResourceManager.GetString("enchantment_aqua_affinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虫殺し.
        /// </summary>
        internal static string enchantment_bane_of_arthropods {
            get {
                return ResourceManager.GetString("enchantment_bane_of_arthropods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爆発耐性.
        /// </summary>
        internal static string enchantment_blast_protection {
            get {
                return ResourceManager.GetString("enchantment_blast_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水中移動.
        /// </summary>
        internal static string enchantment_depth_strider {
            get {
                return ResourceManager.GetString("enchantment_depth_strider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 効率.
        /// </summary>
        internal static string enchantment_efficiency {
            get {
                return ResourceManager.GetString("enchantment_efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 落下軽減.
        /// </summary>
        internal static string enchantment_feather_falling {
            get {
                return ResourceManager.GetString("enchantment_feather_falling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火属性.
        /// </summary>
        internal static string enchantment_fire_aspect {
            get {
                return ResourceManager.GetString("enchantment_fire_aspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 防火.
        /// </summary>
        internal static string enchantment_fire_protection {
            get {
                return ResourceManager.GetString("enchantment_fire_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火炎.
        /// </summary>
        internal static string enchantment_flame {
            get {
                return ResourceManager.GetString("enchantment_flame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸運.
        /// </summary>
        internal static string enchantment_fortune {
            get {
                return ResourceManager.GetString("enchantment_fortune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 氷上歩行.
        /// </summary>
        internal static string enchantment_frost_walker {
            get {
                return ResourceManager.GetString("enchantment_frost_walker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無限.
        /// </summary>
        internal static string enchantment_infinity {
            get {
                return ResourceManager.GetString("enchantment_infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ノックバック.
        /// </summary>
        internal static string enchantment_knockback {
            get {
                return ResourceManager.GetString("enchantment_knockback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイテムボーナス.
        /// </summary>
        internal static string enchantment_looting {
            get {
                return ResourceManager.GetString("enchantment_looting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宝釣り.
        /// </summary>
        internal static string enchantment_luck_of_the_sea {
            get {
                return ResourceManager.GetString("enchantment_luck_of_the_sea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入れ食い.
        /// </summary>
        internal static string enchantment_lure {
            get {
                return ResourceManager.GetString("enchantment_lure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修繕.
        /// </summary>
        internal static string enchantment_mending {
            get {
                return ResourceManager.GetString("enchantment_mending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パワー.
        /// </summary>
        internal static string enchantment_power {
            get {
                return ResourceManager.GetString("enchantment_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 間接攻撃耐性.
        /// </summary>
        internal static string enchantment_projectile_protection {
            get {
                return ResourceManager.GetString("enchantment_projectile_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保護.
        /// </summary>
        internal static string enchantment_protection {
            get {
                return ResourceManager.GetString("enchantment_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 衝撃.
        /// </summary>
        internal static string enchantment_punch {
            get {
                return ResourceManager.GetString("enchantment_punch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水中呼吸.
        /// </summary>
        internal static string enchantment_respiration {
            get {
                return ResourceManager.GetString("enchantment_respiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鋭さ.
        /// </summary>
        internal static string enchantment_sharpness {
            get {
                return ResourceManager.GetString("enchantment_sharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シルクタッチ.
        /// </summary>
        internal static string enchantment_silk_touch {
            get {
                return ResourceManager.GetString("enchantment_silk_touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聖なる力.
        /// </summary>
        internal static string enchantment_smite {
            get {
                return ResourceManager.GetString("enchantment_smite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to とげ.
        /// </summary>
        internal static string enchantment_thorns {
            get {
                return ResourceManager.GetString("enchantment_thorns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 耐久力.
        /// </summary>
        internal static string enchantment_unbreaking {
            get {
                return ResourceManager.GetString("enchantment_unbreaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーのIPアドレス.
        /// </summary>
        internal static string server_config_address {
            get {
                return ResourceManager.GetString("server_config_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームの難易度.
        /// </summary>
        internal static string server_config_difficulty {
            get {
                return ResourceManager.GetString("server_config_difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フラットジェネレータの設定.
        /// </summary>
        internal static string server_config_flatGeneratorOptions {
            get {
                return ResourceManager.GetString("server_config_flatGeneratorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームモード.
        /// </summary>
        internal static string server_config_gameMode {
            get {
                return ResourceManager.GetString("server_config_gameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エンドの生成.
        /// </summary>
        internal static string server_config_generateEnd {
            get {
                return ResourceManager.GetString("server_config_generateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ネザーの生成.
        /// </summary>
        internal static string server_config_generateNether {
            get {
                return ResourceManager.GetString("server_config_generateNether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハードコアモードの有効化.
        /// </summary>
        internal static string server_config_hardcore {
            get {
                return ResourceManager.GetString("server_config_hardcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定ファイルの読み込みエラー.
        /// </summary>
        internal static string server_config_loadError {
            get {
                return ResourceManager.GetString("server_config_loadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル: {0} をバックアップして削除してから起動してください。{1}例外: {2}.
        /// </summary>
        internal static string server_config_loadError_description {
            get {
                return ResourceManager.GetString("server_config_loadError_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 読み込む サブワールド名 &lt;複数可&gt;.
        /// </summary>
        internal static string server_config_loadWorldNames {
            get {
                return ResourceManager.GetString("server_config_loadWorldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メインワールドのジェネレータ &lt;Default / Flat&gt;.
        /// </summary>
        internal static string server_config_mainWorldGenerator {
            get {
                return ResourceManager.GetString("server_config_mainWorldGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 読み込む/生成する メインワールド名.
        /// </summary>
        internal static string server_config_mainWorldName {
            get {
                return ResourceManager.GetString("server_config_mainWorldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーの最大接続台数.
        /// </summary>
        internal static string server_config_maxPlayer {
            get {
                return ResourceManager.GetString("server_config_maxPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ワールドの最大描画距離.
        /// </summary>
        internal static string server_config_maxViewDistance {
            get {
                return ResourceManager.GetString("server_config_maxViewDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xboxアカウントを使用した認証.
        /// </summary>
        internal static string server_config_onlineMode {
            get {
                return ResourceManager.GetString("server_config_onlineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーのポート番号.
        /// </summary>
        internal static string server_config_port {
            get {
                return ResourceManager.GetString("server_config_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVPの有効化.
        /// </summary>
        internal static string server_config_pvp {
            get {
                return ResourceManager.GetString("server_config_pvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーの説明.
        /// </summary>
        internal static string server_config_serverMotd {
            get {
                return ResourceManager.GetString("server_config_serverMotd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スポーン地点の保護の範囲.
        /// </summary>
        internal static string server_config_spawnProtection {
            get {
                return ResourceManager.GetString("server_config_spawnProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホワイトリストの有効化.
        /// </summary>
        internal static string server_config_whitelist {
            get {
                return ResourceManager.GetString("server_config_whitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クロックの低下を検知しました。 名前: {0}.
        /// </summary>
        internal static string server_constantClock_lowTickRate {
            get {
                return ResourceManager.GetString("server_constantClock_lowTickRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リカバリー不可能なエラーが発生しました。.
        /// </summary>
        internal static string server_error_stop {
            get {
                return ResourceManager.GetString("server_error_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MineNET.
        /// </summary>
        internal static string server_name {
            get {
                return ResourceManager.GetString("server_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハンドルされていないデータパケット {0} を受信しました。.
        /// </summary>
        internal static string server_network_dataPacket_notHandle {
            get {
                return ResourceManager.GetString("server_network_dataPacket_notHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データパケットの再送信が行われました。.
        /// </summary>
        internal static string server_network_dataPacket_resend {
            get {
                return ResourceManager.GetString("server_network_dataPacket_resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハンドルされていないMinecraftパケット {0} を受信しました。.
        /// </summary>
        internal static string server_network_minecraft_notHandle {
            get {
                return ResourceManager.GetString("server_network_minecraft_notHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraftパケット {0} を受信しました。 バイト長: {1}.
        /// </summary>
        internal static string server_network_minecraft_receivePacket {
            get {
                return ResourceManager.GetString("server_network_minecraft_receivePacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraftパケット {0} を送信しました。 バイト長: {1}.
        /// </summary>
        internal static string server_network_minecraft_sendPacket {
            get {
                return ResourceManager.GetString("server_network_minecraft_sendPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パケットの受信を強制終了しました。.
        /// </summary>
        internal static string server_network_packetThreadAbort {
            get {
                return ResourceManager.GetString("server_network_packetThreadAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハンドルされていないRakNetパケット {0} を受信しました。.
        /// </summary>
        internal static string server_network_raknet_notHandle {
            get {
                return ResourceManager.GetString("server_network_raknet_notHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セッションが終了しました。&lt;{0}&gt;.
        /// </summary>
        internal static string server_network_raknet_sessionClose {
            get {
                return ResourceManager.GetString("server_network_raknet_sessionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セッションが作成されました。 &lt;{0}&gt; MTUサイズ: {1}.
        /// </summary>
        internal static string server_network_raknet_sessionCreate {
            get {
                return ResourceManager.GetString("server_network_raknet_sessionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} は既にセッションが作成されています。.
        /// </summary>
        internal static string server_network_raknet_sessionCreated {
            get {
                return ResourceManager.GetString("server_network_raknet_sessionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セッション &lt;{0}&gt; は {1} で終了しました。.
        /// </summary>
        internal static string server_network_raknet_sessionDisconnect {
            get {
                return ResourceManager.GetString("server_network_raknet_sessionDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} はセッションが作成されていません。.
        /// </summary>
        internal static string server_network_raknet_sessionNotCreated {
            get {
                return ResourceManager.GetString("server_network_raknet_sessionNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポート番号 {0} でネットワークリスナーを開始しています。.
        /// </summary>
        internal static string server_network_start {
            get {
                return ResourceManager.GetString("server_network_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ネットワークリスナーを開始しました。 起動経過時間: {0}.
        /// </summary>
        internal static string server_network_start_done {
            get {
                return ResourceManager.GetString("server_network_start_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ネットワークリスナーを終了しました。 終了経過時間: {0}.
        /// </summary>
        internal static string server_network_stop {
            get {
                return ResourceManager.GetString("server_network_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} から {1} チャンクのリクエストを受け取りました。.
        /// </summary>
        internal static string server_player_requestChunkRadius {
            get {
                return ResourceManager.GetString("server_player_requestChunkRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} の リクエストチャンクを {1} から {2} に変更しました。.
        /// </summary>
        internal static string server_player_updateChunkRadius {
            get {
                return ResourceManager.GetString("server_player_updateChunkRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] ライブラリ {0} を無効にしました。.
        /// </summary>
        internal static string server_plugin_disable_library {
            get {
                return ResourceManager.GetString("server_plugin_disable_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] パッケージ {0} を無効にしました。.
        /// </summary>
        internal static string server_plugin_disable_package {
            get {
                return ResourceManager.GetString("server_plugin_disable_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] プラグイン {0} を無効にしました。.
        /// </summary>
        internal static string server_plugin_disable_plugin {
            get {
                return ResourceManager.GetString("server_plugin_disable_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] ライブラリ {0} を有効にしました。.
        /// </summary>
        internal static string server_plugin_enable_library {
            get {
                return ResourceManager.GetString("server_plugin_enable_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] パッケージ {0} を有効にしました。.
        /// </summary>
        internal static string server_plugin_enable_package {
            get {
                return ResourceManager.GetString("server_plugin_enable_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] プラグイン {0} を有効にしました。.
        /// </summary>
        internal static string server_plugin_enable_plugin {
            get {
                return ResourceManager.GetString("server_plugin_enable_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル {0} の読み込みに失敗しました。.
        /// </summary>
        internal static string server_plugin_load_error {
            get {
                return ResourceManager.GetString("server_plugin_load_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] ライブラリ {0} を読み込んでいます。.
        /// </summary>
        internal static string server_plugin_load_library {
            get {
                return ResourceManager.GetString("server_plugin_load_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] パッケージ {0} を読み込んでいます。.
        /// </summary>
        internal static string server_plugin_load_package {
            get {
                return ResourceManager.GetString("server_plugin_load_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] プラグイン {0} を読み込んでいます。.
        /// </summary>
        internal static string server_plugin_load_plugin {
            get {
                return ResourceManager.GetString("server_plugin_load_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MineNET サーバーを開始しています。.
        /// </summary>
        internal static string server_start {
            get {
                return ResourceManager.GetString("server_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーが開始しました。.
        /// </summary>
        internal static string server_start_done {
            get {
                return ResourceManager.GetString("server_start_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to helpでコマンド確認して下さい。 起動経過時間: {0}.
        /// </summary>
        internal static string server_start_done2 {
            get {
                return ResourceManager.GetString("server_start_done2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーは終了しました。 終了経過時間: {0}.
        /// </summary>
        internal static string server_stoped {
            get {
                return ResourceManager.GetString("server_stoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーを終了しています。.
        /// </summary>
        internal static string server_stopping {
            get {
                return ResourceManager.GetString("server_stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ワールド &quot;{0}&quot; が作成されました。.
        /// </summary>
        internal static string server_world_create {
            get {
                return ResourceManager.GetString("server_world_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ワールド &quot;{0}&quot; が読み込まれました。.
        /// </summary>
        internal static string server_world_load {
            get {
                return ResourceManager.GetString("server_world_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string server_z {
            get {
                return ResourceManager.GetString("server_z", resourceCulture);
            }
        }
    }
}
