//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineNET.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineNET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   IP アドレスを BAN 一覧に追加します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_ban_description {
            get {
                return ResourceManager.GetString("commands_ban_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイヤー {0} をアクセス禁止にしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_ban_success {
            get {
                return ResourceManager.GetString("commands_ban_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP アドレスを BAN 一覧に追加します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_banip_description {
            get {
                return ResourceManager.GetString("commands_banip_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効な IP アドレスが入力されたか、プレイヤーがオンラインになっていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_banip_invalid {
            get {
                return ResourceManager.GetString("commands_banip_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP アドレス {0} をアクセス禁止にしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_banip_success {
            get {
                return ResourceManager.GetString("commands_banip_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} に属する IP アドレス {0} をアクセス禁止にしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_banip_success_players {
            get {
                return ResourceManager.GetString("commands_banip_success_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイヤーからオペレーターのステータスを取り消す。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_deop_description {
            get {
                return ResourceManager.GetString("commands_deop_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} からオペレーター権限を剥奪しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_deop_success {
            get {
                return ResourceManager.GetString("commands_deop_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータス効果を追加/除去します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_effect_description {
            get {
                return ResourceManager.GetString("commands_effect_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} は効果を受けていないので、除去できませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_effect_failure_notActive_all {
            get {
                return ResourceManager.GetString("commands_effect_failure_notActive_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に効果を付与することはできません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_effect_failure_notAMob {
            get {
                return ResourceManager.GetString("commands_effect_failure_notAMob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {2} に {0} * {1} を {3} 秒間与えました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_effect_success {
            get {
                return ResourceManager.GetString("commands_effect_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} からすべての効果を除去しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_effect_success_removed_all {
            get {
                return ResourceManager.GetString("commands_effect_success_removed_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択中のエンチャントは対象のアイテムに付加できません: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_enchant_cantEnchant {
            get {
                return ResourceManager.GetString("commands_enchant_cantEnchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択中のプレイヤーのアイテムにエンチャントを付与する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_enchant_description {
            get {
                return ResourceManager.GetString("commands_enchant_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} はレベル {1} に対応していません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_enchant_invalidLevel {
            get {
                return ResourceManager.GetString("commands_enchant_invalidLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} のエンチャントに成功しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_enchant_success {
            get {
                return ResourceManager.GetString("commands_enchant_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイヤーのゲーム モードを設定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_gamemode_description {
            get {
                return ResourceManager.GetString("commands_gamemode_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   §cゲーム モード &apos;{0}&apos; は無効です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_gamemode_fail_invalid {
            get {
                return ResourceManager.GetString("commands_gamemode_fail_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} のゲームモードを {0} に設定しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_gamemode_success_other {
            get {
                return ResourceManager.GetString("commands_gamemode_success_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたのゲームモードを {0} に設定しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_gamemode_success_self {
            get {
                return ResourceManager.GetString("commands_gamemode_success_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   §cセレクターに合う対象がありません  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_generic_noTargetMatch {
            get {
                return ResourceManager.GetString("commands_generic_noTargetMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実装されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_generic_notimplemented {
            get {
                return ResourceManager.GetString("commands_generic_notimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   §c指定されたプレイヤーが見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_generic_player_notFound {
            get {
                return ResourceManager.GetString("commands_generic_player_notFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   §cセレクターはプレイヤーの型にする必要があります  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_generic_targetNotPlayer {
            get {
                return ResourceManager.GetString("commands_generic_targetNotPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   §c不明なコマンド: {0}。このコマンドが存在し、これを使用する権限があることを確認してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_generic_unknown {
            get {
                return ResourceManager.GetString("commands_generic_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイヤーにアイテムを与える。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_give_description {
            get {
                return ResourceManager.GetString("commands_give_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {2} に {0} を {1} 個与えました  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_give_success {
            get {
                return ResourceManager.GetString("commands_give_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を {1}個受け取りました  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_give_successRecipient {
            get {
                return ResourceManager.GetString("commands_give_successRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンドのヘルプ/一覧を呼び出す。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_help_description {
            get {
                return ResourceManager.GetString("commands_help_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --- ヘルプ ページの {0} ／ {1} ページを表示 (/help &lt;ページ番号&gt;) --- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_help_header {
            get {
                return ResourceManager.GetString("commands_help_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバー上のプレイヤーの一覧を表示する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_list_description {
            get {
                return ResourceManager.GetString("commands_list_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたに関するメッセージを表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_me_description {
            get {
                return ResourceManager.GetString("commands_me_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイヤーにオペレーターのステータスを与える。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_op_description {
            get {
                return ResourceManager.GetString("commands_op_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} にオペレーター権限を付与しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_op_success {
            get {
                return ResourceManager.GetString("commands_op_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャットで他のプレイヤーにメッセージを送信する_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_say_description {
            get {
                return ResourceManager.GetString("commands_say_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーを停止する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_stop_description {
            get {
                return ResourceManager.GetString("commands_stop_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 人または複数のプレイヤーにプライベート メッセージを送信する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_tell_description {
            get {
                return ResourceManager.GetString("commands_tell_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイヤー {0} のアクセス禁止を解除できませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_unban_failed {
            get {
                return ResourceManager.GetString("commands_unban_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイヤー {0} のアクセス禁止を解除しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_unban_success {
            get {
                return ResourceManager.GetString("commands_unban_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IPアドレスが無効です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_unbanip_invalid {
            get {
                return ResourceManager.GetString("commands_unbanip_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP アドレス {0} のアクセス禁止を解除しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_unbanip_success {
            get {
                return ResourceManager.GetString("commands_unbanip_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} をホワイトリストに追加しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_whitelist_add_success {
            get {
                return ResourceManager.GetString("commands_whitelist_add_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーのホワイトリストを管理する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_whitelist_description {
            get {
                return ResourceManager.GetString("commands_whitelist_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホワイトリストを無効にしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_whitelist_disabled {
            get {
                return ResourceManager.GetString("commands_whitelist_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホワイトリストを有効にしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_whitelist_enabled {
            get {
                return ResourceManager.GetString("commands_whitelist_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホワイトリストには {0} 人 (サーバー全体では {1} 人) のプレイヤーがいます: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_whitelist_list {
            get {
                return ResourceManager.GetString("commands_whitelist_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} をホワイトリストから削除しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_whitelist_remove_success {
            get {
                return ResourceManager.GetString("commands_whitelist_remove_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイヤーの経験値を増加/減少させます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_xp_description {
            get {
                return ResourceManager.GetString("commands_xp_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイヤーに負の経験値を与えることはできません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_xp_failure_widthdrawXp {
            get {
                return ResourceManager.GetString("commands_xp_failure_widthdrawXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} に経験値 {0} を与えまし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_xp_success {
            get {
                return ResourceManager.GetString("commands_xp_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} に {0} レベルを付与しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_xp_success_levels {
            get {
                return ResourceManager.GetString("commands_xp_success_levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} から {0} レベルを剥奪しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string commands_xp_success_negative_levels {
            get {
                return ResourceManager.GetString("commands_xp_success_negative_levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   吸収 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_absorption {
            get {
                return ResourceManager.GetString("effect_absorption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   目つぶし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_blindness {
            get {
                return ResourceManager.GetString("effect_blindness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   毒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_fatal_poison {
            get {
                return ResourceManager.GetString("effect_fatal_poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   耐火 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_fire_resistance {
            get {
                return ResourceManager.GetString("effect_fire_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   勤勉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_haste {
            get {
                return ResourceManager.GetString("effect_haste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HPブースト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_health_boost {
            get {
                return ResourceManager.GetString("effect_health_boost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空腹 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_hunger {
            get {
                return ResourceManager.GetString("effect_hunger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダメージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_instant_damage {
            get {
                return ResourceManager.GetString("effect_instant_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回復 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_instant_health {
            get {
                return ResourceManager.GetString("effect_instant_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不可視 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_invisibility {
            get {
                return ResourceManager.GetString("effect_invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   跳躍 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_jump_boost {
            get {
                return ResourceManager.GetString("effect_jump_boost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   浮遊 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_levitation {
            get {
                return ResourceManager.GetString("effect_levitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   疲労 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_mining_fatigue {
            get {
                return ResourceManager.GetString("effect_mining_fatigue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   目まい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_nausea {
            get {
                return ResourceManager.GetString("effect_nausea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   暗視 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_night_vision {
            get {
                return ResourceManager.GetString("effect_night_vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   毒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_poison {
            get {
                return ResourceManager.GetString("effect_poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_regeneration {
            get {
                return ResourceManager.GetString("effect_regeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   耐性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_resistance {
            get {
                return ResourceManager.GetString("effect_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   飽和 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_saturation {
            get {
                return ResourceManager.GetString("effect_saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   鈍化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_slowness {
            get {
                return ResourceManager.GetString("effect_slowness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スピード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_speed {
            get {
                return ResourceManager.GetString("effect_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_strength {
            get {
                return ResourceManager.GetString("effect_strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水中呼吸 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_water_breathing {
            get {
                return ResourceManager.GetString("effect_water_breathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   弱体化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_weakness {
            get {
                return ResourceManager.GetString("effect_weakness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string effect_wither {
            get {
                return ResourceManager.GetString("effect_wither", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水中作業 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_aqua_affinity {
            get {
                return ResourceManager.GetString("enchantment_aqua_affinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   虫殺し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_bane_of_arthropods {
            get {
                return ResourceManager.GetString("enchantment_bane_of_arthropods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   爆発耐性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_blast_protection {
            get {
                return ResourceManager.GetString("enchantment_blast_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水中移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_depth_strider {
            get {
                return ResourceManager.GetString("enchantment_depth_strider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   効率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_efficiency {
            get {
                return ResourceManager.GetString("enchantment_efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   落下軽減 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_feather_falling {
            get {
                return ResourceManager.GetString("enchantment_feather_falling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火属性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_fire_aspect {
            get {
                return ResourceManager.GetString("enchantment_fire_aspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防火 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_fire_protection {
            get {
                return ResourceManager.GetString("enchantment_fire_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火炎 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_flame {
            get {
                return ResourceManager.GetString("enchantment_flame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   幸運 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_fortune {
            get {
                return ResourceManager.GetString("enchantment_fortune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   氷上歩行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_frost_walker {
            get {
                return ResourceManager.GetString("enchantment_frost_walker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_infinity {
            get {
                return ResourceManager.GetString("enchantment_infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノックバック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_knockback {
            get {
                return ResourceManager.GetString("enchantment_knockback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムボーナス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_looting {
            get {
                return ResourceManager.GetString("enchantment_looting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   宝釣り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_luck_of_the_sea {
            get {
                return ResourceManager.GetString("enchantment_luck_of_the_sea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入れ食い に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_lure {
            get {
                return ResourceManager.GetString("enchantment_lure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   修繕 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_mending {
            get {
                return ResourceManager.GetString("enchantment_mending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パワー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_power {
            get {
                return ResourceManager.GetString("enchantment_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   間接攻撃耐性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_projectile_protection {
            get {
                return ResourceManager.GetString("enchantment_projectile_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保護 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_protection {
            get {
                return ResourceManager.GetString("enchantment_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   衝撃 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_punch {
            get {
                return ResourceManager.GetString("enchantment_punch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水中呼吸 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_respiration {
            get {
                return ResourceManager.GetString("enchantment_respiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   鋭さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_sharpness {
            get {
                return ResourceManager.GetString("enchantment_sharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シルクタッチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_silk_touch {
            get {
                return ResourceManager.GetString("enchantment_silk_touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   聖なる力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_smite {
            get {
                return ResourceManager.GetString("enchantment_smite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   とげ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_thorns {
            get {
                return ResourceManager.GetString("enchantment_thorns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   耐久力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enchantment_unbreaking {
            get {
                return ResourceManager.GetString("enchantment_unbreaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーのIPアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_address {
            get {
                return ResourceManager.GetString("server_config_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲームの難易度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_difficulty {
            get {
                return ResourceManager.GetString("server_config_difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フラットジェネレータの設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_flatGeneratorOptions {
            get {
                return ResourceManager.GetString("server_config_flatGeneratorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲームモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_gameMode {
            get {
                return ResourceManager.GetString("server_config_gameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エンドの生成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_generateEnd {
            get {
                return ResourceManager.GetString("server_config_generateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネザーの生成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_generateNether {
            get {
                return ResourceManager.GetString("server_config_generateNether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハードコアモードの有効化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_hardcore {
            get {
                return ResourceManager.GetString("server_config_hardcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイルの読み込みエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_loadError {
            get {
                return ResourceManager.GetString("server_config_loadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル: {0} をバックアップして削除してから起動してください。{1}例外: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_loadError_description {
            get {
                return ResourceManager.GetString("server_config_loadError_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込む サブワールド名 &lt;複数可&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_loadWorldNames {
            get {
                return ResourceManager.GetString("server_config_loadWorldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メインワールドのジェネレータ &lt;Default / Flat&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_mainWorldGenerator {
            get {
                return ResourceManager.GetString("server_config_mainWorldGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込む/生成する メインワールド名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_mainWorldName {
            get {
                return ResourceManager.GetString("server_config_mainWorldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーの最大接続台数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_maxPlayer {
            get {
                return ResourceManager.GetString("server_config_maxPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワールドの最大描画距離 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_maxViewDistance {
            get {
                return ResourceManager.GetString("server_config_maxViewDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Xboxアカウントを使用した認証 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_onlineMode {
            get {
                return ResourceManager.GetString("server_config_onlineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーのポート番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_port {
            get {
                return ResourceManager.GetString("server_config_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PVPの有効化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_pvp {
            get {
                return ResourceManager.GetString("server_config_pvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーの説明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_serverMotd {
            get {
                return ResourceManager.GetString("server_config_serverMotd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スポーン地点の保護の範囲 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_spawnProtection {
            get {
                return ResourceManager.GetString("server_config_spawnProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホワイトリストの有効化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_config_whitelist {
            get {
                return ResourceManager.GetString("server_config_whitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クロックの低下を検知しました。 名前: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_constantClock_lowTickRate {
            get {
                return ResourceManager.GetString("server_constantClock_lowTickRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リカバリー不可能なエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_error_stop {
            get {
                return ResourceManager.GetString("server_error_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MineNET に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_name {
            get {
                return ResourceManager.GetString("server_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハンドルされていないデータパケット {0} を受信しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_dataPacket_notHandle {
            get {
                return ResourceManager.GetString("server_network_dataPacket_notHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データパケットの再送信が行われました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_dataPacket_resend {
            get {
                return ResourceManager.GetString("server_network_dataPacket_resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハンドルされていないMinecraftパケット {0} を受信しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_minecraft_notHandle {
            get {
                return ResourceManager.GetString("server_network_minecraft_notHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minecraftパケット {0} を受信しました。 バイト長: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_minecraft_receivePacket {
            get {
                return ResourceManager.GetString("server_network_minecraft_receivePacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minecraftパケット {0} を送信しました。 バイト長: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_minecraft_sendPacket {
            get {
                return ResourceManager.GetString("server_network_minecraft_sendPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パケットの受信を強制終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_packetThreadAbort {
            get {
                return ResourceManager.GetString("server_network_packetThreadAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハンドルされていないRakNetパケット {0} を受信しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_raknet_notHandle {
            get {
                return ResourceManager.GetString("server_network_raknet_notHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セッションが終了しました。&lt;{0}&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_raknet_sessionClose {
            get {
                return ResourceManager.GetString("server_network_raknet_sessionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セッションが作成されました。 &lt;{0}&gt; MTUサイズ: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_raknet_sessionCreate {
            get {
                return ResourceManager.GetString("server_network_raknet_sessionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} は既にセッションが作成されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_raknet_sessionCreated {
            get {
                return ResourceManager.GetString("server_network_raknet_sessionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セッション &lt;{0}&gt; は {1} で終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_raknet_sessionDisconnect {
            get {
                return ResourceManager.GetString("server_network_raknet_sessionDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} はセッションが作成されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_raknet_sessionNotCreated {
            get {
                return ResourceManager.GetString("server_network_raknet_sessionNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポート番号 {0} でネットワークリスナーを開始しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_start {
            get {
                return ResourceManager.GetString("server_network_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワークリスナーを開始しました。 起動経過時間: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_start_done {
            get {
                return ResourceManager.GetString("server_network_start_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワークリスナーを終了しました。 終了経過時間: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_network_stop {
            get {
                return ResourceManager.GetString("server_network_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} から {1} チャンクのリクエストを受け取りました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_player_requestChunkRadius {
            get {
                return ResourceManager.GetString("server_player_requestChunkRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} の リクエストチャンクを {1} から {2} に変更しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_player_updateChunkRadius {
            get {
                return ResourceManager.GetString("server_player_updateChunkRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] ライブラリ {0} を無効にしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_plugin_disable_library {
            get {
                return ResourceManager.GetString("server_plugin_disable_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] パッケージ {0} を無効にしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_plugin_disable_package {
            get {
                return ResourceManager.GetString("server_plugin_disable_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] プラグイン {0} を無効にしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_plugin_disable_plugin {
            get {
                return ResourceManager.GetString("server_plugin_disable_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] ライブラリ {0} を有効にしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_plugin_enable_library {
            get {
                return ResourceManager.GetString("server_plugin_enable_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] パッケージ {0} を有効にしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_plugin_enable_package {
            get {
                return ResourceManager.GetString("server_plugin_enable_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] プラグイン {0} を有効にしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_plugin_enable_plugin {
            get {
                return ResourceManager.GetString("server_plugin_enable_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] ライブラリ {0} を読み込んでいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_plugin_load_library {
            get {
                return ResourceManager.GetString("server_plugin_load_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] パッケージ {0} を読み込んでいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_plugin_load_package {
            get {
                return ResourceManager.GetString("server_plugin_load_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] プラグイン {0} を読み込んでいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_plugin_load_plugin {
            get {
                return ResourceManager.GetString("server_plugin_load_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MineNET サーバーを開始しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_start {
            get {
                return ResourceManager.GetString("server_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーが開始しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_start_done {
            get {
                return ResourceManager.GetString("server_start_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   helpでコマンド確認して下さい。 起動経過時間: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_start_done2 {
            get {
                return ResourceManager.GetString("server_start_done2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーは終了しました。 終了経過時間: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_stoped {
            get {
                return ResourceManager.GetString("server_stoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーを終了しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_stopping {
            get {
                return ResourceManager.GetString("server_stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワールド &quot;{0}&quot; が作成されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_world_create {
            get {
                return ResourceManager.GetString("server_world_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワールド &quot;{0}&quot; が読み込まれました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_world_load {
            get {
                return ResourceManager.GetString("server_world_load", resourceCulture);
            }
        }
    }
}
