//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineNET.Lang {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineNET.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   BlockFactoryを初期化しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string server_block_init {
            get {
                return ResourceManager.GetString("server_block_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemFactoryを初期化しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string server_item_init {
            get {
                return ResourceManager.GetString("server_item_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PacketHandlerを開始しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string server_net_packetHandlerStart {
            get {
                return ResourceManager.GetString("server_net_packetHandlerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Networkを開始しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string server_net_start {
            get {
                return ResourceManager.GetString("server_net_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスナーをポート {0} で開始しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string server_net_started {
            get {
                return ResourceManager.GetString("server_net_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PacketPoolを初期化しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string server_packet_init {
            get {
                return ResourceManager.GetString("server_packet_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MineNETServerを開始しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string server_start {
            get {
                return ResourceManager.GetString("server_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーが開始されました。　起動時間: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string server_started {
            get {
                return ResourceManager.GetString("server_started", resourceCulture);
            }
        }
    }
}
